version: "3.8"

services:

  redis:
    image: redis:7
    container_name: chat-redis
    ports:
      - "6379:6379"
  
  server:
    build: ./server
    depends_on:
      - redis
    environment:
      - PORT=3001
    expose:
      - 3001
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server