events {}
http {
    upstream chat_servers {
        server server:3001;
    }
    server {
        listen 80;
        access_log off;
        
        location / {
            proxy_pass http://chat_servers;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}